//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.09 at 05:30:31 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://testdatabuilder.pahlsoft.com")
package com.pahlsoft.testdatabuilder.model;
